#ifndef DEBUG_H
#define DEBUG_H

#define DEBUG_ORBIT 0
#define DEBUG_IMU 0
#define DEBUG_TSSP 0
#define DEBUG_BALL_DATA 0
#define DEBUG_LIGHT 0
#define DEBUG_LINE 0
#define DEBUG_AVOIDANCE 0
#define DEBUG_CAMERA 0
#define DEBUG_POSITION 0

#define DEBUG_MANUAL 1

#define DEBUG_ANY DEBUG_MANUAL || DEBUG_ORBIT || DEBUG_IMU || DEBUG_TSSP || DEBUG_BALL_DATA || DEBUG_LIGHT || DEBUG_LINE || DEBUG_AVOIDANCE || DEBUG_CAMERA || DEBUG_POSITION

#endif
